set-option -ga terminal-overrides ",foot:RGB"

set-environment -g FZF_DEFAULT_OPTS " --color=bg+:#313244,bg:#1e1e2e,spinner:#f5e0dc,hl:#f38ba8 \
  --color=fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc \
  --color=marker:#f5e0dc,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8 \
  --prompt '󰭎 ' --pointer ' λ' --layout=reverse --border horizontal --height 40
"

set -g default-shell /usr/bin/zsh
set -g mouse on
set -s escape-time 0
set-option -g status-position top
set-window-option -g mode-keys vi

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-sensible'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-yank'
# Catppuccin
set -g @catppuccin_flavour 'mocha' # or frappe, macchiato, mocha
set -g @catppuccin_window_right_separator ""
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_middle_separator " ~ "

set -g @catppuccin_window_default_fill "none"
set -g @catppuccin_window_current_text "#{pane_current_path}"
set -g @catppuccin_window_current_fill "all"

set -g @catppuccin_status_modules_right "session user"
set -g @catppuccin_status_left_separator  ""
set -g @catppuccin_status_right_separator ""

set -g @catppuccin_date_time_text "%Y-%m-%d %H:%M:%S"
set -g @catppuccin_window_status_enable "no"

bind r source-file ~/.config/tmux/tmux.conf
set -g base-index 1

bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle 
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 

bind-key Enter if-shell "tmux list-windows | grep -q terminal" "select-window -t terminal" "neww -n terminal -c '#{pane_current_path}'"
bind-key "/" run-shell "~/.local/bin/tmux/main"
bind-key "'" switch-client -n
bind-key ";" switch-client -p

# forget the find window.  That is for chumps (Thanks primeagen very cool)
bind-key -r f run-shell "tmux neww ~/.local/bin/tmux/tmux-sessionaizer"
bind-key -r g run-shell "tmux neww ~/.local/bin/tmux/tmux-sessionaizer global"
bind-key -r "." run-shell "tmux neww fzf"

run '/usr/share/tmux-plugin-manager/tpm'

run-shell "~/.local/bin/tmux/install_plugins"
