general {
    lock_cmd = sleep 5;pamixer -m;hyprctl dispatch dpms off
    ignore_dbus_inhibit = false
}

listener {
    timeout = 600
    on-timeout = pamixer -m;hyprctl dispatch dpms off
    on-resume = pamixer -u;hyprctl dispatch dpms on
}

listener {
    timeout = 630 
    on-timeout = hyprlock
}
