general {
    lock_cmd = pamixer -m 
    unlock_cmd = pamixer -u 
    ignore_dbus_inhibit = false
}

listener {
    timeout = 300
    on-timeout = pamixer -m;hyprctl dispatch dpms off
    on-resume = pamixer -u;hyprctl dispatch dpms on
}

listener {
    timeout = 330 
    on-timeout = hyprlock
}

listener {
    timeout = 10800
    on-timeout = systemctl hibernate
}
